# ecotone_products_data.py - Produits extraits de Zone Ecotone
# Source: https://zone-ecotone.com/collections/trouver-des-appats-pour-une-chasse-reussie
# Date d'extraction: Janvier 2026

import uuid
from datetime import datetime, timezone

# Marques identifiées
ECOTONE_BRANDS = {
    "buck_expert": "Buck Expert",
    "maniaque_prospection": "Maniaque de Prospection",
    "meunerie_soucy": "Meunerie Soucy",
    "extremes_cg": "Produits Extrêmes C.G.",
    "tinks": "Tink's",
    "glands_chene": "Glands de Chêne",
    "sel_drummond": "Sel Drummond",
    "traktiq": "Traktiq",
    "moultrie": "Moultrie"
}

# Catégories de produits
ECOTONE_CATEGORIES = {
    "urine": "Urine / Leurre sexuel",
    "mineral": "Minéraux / Saline",
    "poudre": "Poudre attractante",
    "liquide": "Liquide / Coulis",
    "gel": "Gel attractant",
    "granules": "Granules / Moulée",
    "bloc": "Bloc pressé",
    "kit": "Kit / Ensemble",
    "accessoire": "Accessoire d'appâtage"
}

# Espèces ciblées
TARGET_SPECIES = {
    "orignal": "Orignal",
    "chevreuil": "Chevreuil",
    "ours": "Ours",
    "cervides": "Cervidés (Multi-espèces)"
}

def generate_product_id():
    return str(uuid.uuid4())

# Base de données des produits extraits
ECOTONE_PRODUCTS = [
    # ========== PAGE 1 ==========
    {
        "id": generate_product_id(),
        "name": "Poudre attractante orignal Bull Fever - Anis",
        "brand": "Produits Extrêmes C.G.",
        "price": 24.99,
        "category": "poudre",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal"],
        "format": "Poudre",
        "flavor": "Anis",
        "product_url": "https://zone-ecotone.com/products/poudre-attractante-orignal-bull-fever-anis-extremes-c-g",
        "image_url": "https://zone-ecotone.com/cdn/shop/products/poudre-attractante-orignal-bull-fever-anis.jpg",
        "availability": "en_magasin",
        "attraction_type": ["odeur", "olfactif"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Mélange Mud 7kg pour vasière Orignal",
        "brand": "Meunerie Soucy",
        "price": 29.99,
        "category": "mineral",
        "sub_category": "vasière",
        "target_species": ["orignal"],
        "format": "7kg",
        "weight": 7000,
        "product_url": "https://zone-ecotone.com/products/melange-mud-7kg-pour-vasiere-orignal-de-meunerie-soucy",
        "availability": "en_magasin",
        "attraction_type": ["minéral", "vasière"],
        "application_mode": "sol",
        "season": ["été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Poudre d'urine à 100% pour salines orignal ou chevreuil",
        "brand": "Maniaque de Prospection",
        "price": 19.99,
        "category": "urine",
        "sub_category": "saline",
        "target_species": ["orignal", "chevreuil"],
        "format": "Poudre",
        "product_url": "https://zone-ecotone.com/products/poudres-100-urine-orignal-ou-chevreuil-par-maniaque-de-prospection",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "olfactif"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Vasière extrême 7kg Orignal",
        "brand": "Produits Extrêmes C.G.",
        "price": 37.99,
        "category": "mineral",
        "sub_category": "vasière",
        "target_species": ["orignal"],
        "format": "7kg",
        "weight": 7000,
        "product_url": "https://zone-ecotone.com/products/vasiere-extreme-7kg-orignal-de-produits-extremes-c-g",
        "availability": "en_stock",
        "attraction_type": ["minéral", "vasière"],
        "application_mode": "sol",
        "season": ["été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine de jument orignal en trio",
        "brand": "Buck Expert",
        "price": 47.99,
        "category": "urine",
        "sub_category": "leurre_sexuel",
        "target_species": ["orignal"],
        "format": "Trio (3 bouteilles)",
        "product_url": "https://zone-ecotone.com/products/urine-de-jument-orignal-en-trio-buck-expert",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "sexuel"],
        "application_mode": "vaporisation",
        "season": ["rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Chaudière minéraux 18kg Orignal",
        "brand": "Produits Extrêmes C.G.",
        "price": 59.99,
        "category": "mineral",
        "sub_category": "minéraux",
        "target_species": ["orignal"],
        "format": "18kg (Chaudière)",
        "weight": 18000,
        "product_url": "https://zone-ecotone.com/products/chaudiere-mineraux-18kg-orignal-de-produits-extremes-c-g",
        "availability": "en_stock",
        "attraction_type": ["minéral", "nutritif"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Mélange Smog Chevreuil ou Orignal",
        "brand": "Meunerie Soucy",
        "price": 6.99,
        "category": "poudre",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal", "chevreuil"],
        "format": "Poudre",
        "variants": ["Pomme", "Banane", "Anis"],
        "product_url": "https://zone-ecotone.com/products/melange-smog-chevreuil-ou-orignal-de-meunerie-soucy",
        "availability": "en_magasin",
        "attraction_type": ["odeur", "fruité"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Chaudière de minéraux pour orignal - 20 kg",
        "brand": "Meunerie Soucy",
        "price": 49.99,
        "category": "mineral",
        "sub_category": "minéraux",
        "target_species": ["orignal"],
        "format": "20kg (Chaudière)",
        "weight": 20000,
        "product_url": "https://zone-ecotone.com/products/chaudiere-de-mineraux-pour-orignal-20-kg-meunerie-soucy",
        "availability": "en_magasin",
        "attraction_type": ["minéral", "nutritif"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Prospection orignal, ensemble",
        "brand": "Maniaque de Prospection",
        "price": 44.99,
        "category": "kit",
        "sub_category": "ensemble",
        "target_species": ["orignal"],
        "format": "Kit complet",
        "product_url": "https://zone-ecotone.com/products/prospection-orignal-ensemble-par-maniaque-de-prospection",
        "availability": "en_magasin",
        "attraction_type": ["multiple"],
        "application_mode": "multiple",
        "season": ["été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Prospection orignal, minéraux 25kg",
        "brand": "Maniaque de Prospection",
        "price": 59.99,
        "category": "mineral",
        "sub_category": "minéraux",
        "target_species": ["orignal"],
        "format": "25kg",
        "weight": 25000,
        "product_url": "https://zone-ecotone.com/products/prospection-orignal-mineraux-25kg-par-maniaque-de-prospection",
        "availability": "en_stock",
        "attraction_type": ["minéral", "nutritif"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Boîte minéraux pour orignal",
        "brand": "Produits Extrêmes C.G.",
        "price": 69.99,
        "category": "mineral",
        "sub_category": "minéraux",
        "target_species": ["orignal"],
        "format": "Boîte",
        "product_url": "https://zone-ecotone.com/products/boite-mineraux-pour-orignal-de-produits-extremes-c-g",
        "availability": "en_magasin",
        "attraction_type": ["minéral", "nutritif"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Mixte attractif orignal, épicéa",
        "brand": "Maniaque de Prospection",
        "price": 24.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal"],
        "format": "Liquide/Mixte",
        "flavor": "Épicéa",
        "product_url": "https://zone-ecotone.com/products/mixte-attractif-orignal-epicea-par-maniaque-de-prospection",
        "availability": "en_stock",
        "attraction_type": ["odeur", "végétal"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Liquide attractif noir intense orignal",
        "brand": "Maniaque de Prospection",
        "price": 24.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/liquide-attractif-noir-intense-orignal-par-maniaque-de-prospection",
        "availability": "en_magasin",
        "attraction_type": ["odeur", "intense"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Mixte attractif orignal, ramure",
        "brand": "Maniaque de Prospection",
        "price": 24.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal"],
        "format": "Liquide/Mixte",
        "flavor": "Ramure",
        "product_url": "https://zone-ecotone.com/products/mixte-attractif-orignal-ramure-par-maniaque-de-prospection",
        "availability": "en_magasin",
        "attraction_type": ["odeur", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Mixte attractif orignal, sagittaria boréal",
        "brand": "Maniaque de Prospection",
        "price": 24.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal"],
        "format": "Liquide/Mixte",
        "flavor": "Sagittaria boréal",
        "product_url": "https://zone-ecotone.com/products/mixte-attractif-orignal-sagittaria-boreal-maniaque-de-prospection",
        "availability": "en_magasin",
        "attraction_type": ["odeur", "végétal"],
        "application_mode": "sol",
        "season": ["été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Mixte attractif orignal, salix naturel",
        "brand": "Maniaque de Prospection",
        "price": 24.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal"],
        "format": "Liquide/Mixte",
        "flavor": "Salix (Saule)",
        "product_url": "https://zone-ecotone.com/products/mixte-attractif-orignal-salix-naturel-par-maniaque-de-prospection",
        "availability": "en_stock",
        "attraction_type": ["odeur", "végétal"],
        "application_mode": "sol",
        "season": ["été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Bâtonnets d'encens orignal",
        "brand": "Tink's",
        "price": 34.99,
        "category": "accessoire",
        "sub_category": "encens",
        "target_species": ["orignal"],
        "format": "Bâtonnets",
        "product_url": "https://zone-ecotone.com/products/batonnets-dencens-orignal-de-tinks",
        "availability": "en_stock",
        "attraction_type": ["odeur", "diffuseur"],
        "application_mode": "brûlage",
        "season": ["rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Leurre olfactif brumisateur femelle orignal en chaleur",
        "brand": "Tink's",
        "price": 21.99,
        "category": "urine",
        "sub_category": "leurre_sexuel",
        "target_species": ["orignal"],
        "format": "Brumisateur",
        "product_url": "https://zone-ecotone.com/products/leurre-olfactif-brumisateur-orignal-en-rut-de-tinks",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "sexuel"],
        "application_mode": "vaporisation",
        "season": ["rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Gel sexuel intense orignal",
        "brand": "Maniaque de Prospection",
        "price": 24.99,
        "category": "gel",
        "sub_category": "leurre_sexuel",
        "target_species": ["orignal"],
        "format": "Gel",
        "product_url": "https://zone-ecotone.com/products/gel-sexuel-intense-orignal-par-maniaque-de-prospection",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "sexuel"],
        "application_mode": "tronc",
        "season": ["rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine d'orignal mâle",
        "brand": "Meunerie Soucy",
        "price": 29.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-dorignal-male-de-soucy",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    
    # ========== PAGE 2 ==========
    {
        "id": generate_product_id(),
        "name": "Urine d'orignal femelle",
        "brand": "Meunerie Soucy",
        "price": 29.99,
        "category": "urine",
        "sub_category": "leurre_sexuel",
        "target_species": ["orignal"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-dorignal-femelle-de-soucy",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "sexuel"],
        "application_mode": "sol",
        "season": ["rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine naturelle Xtreme mâle dominant orignal",
        "brand": "Buck Expert",
        "price": 34.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-naturelle-xtreme-male-dominant-de-buck-expert",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine naturelle Xtreme femelle orignal en chaleur",
        "brand": "Buck Expert",
        "price": 34.99,
        "category": "urine",
        "sub_category": "leurre_sexuel",
        "target_species": ["orignal"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-naturelle-xtreme-femelle-en-chaleur-de-buck-expert",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "sexuel"],
        "application_mode": "sol",
        "season": ["rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine naturelle Xtreme jeune mâle orignal",
        "brand": "Buck Expert",
        "price": 34.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-naturelle-xtreme-jeune-male-de-buck-expert",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Bâtonnets d'odeur d'urine concentrés mâle mature orignal",
        "brand": "Buck Expert",
        "price": 14.99,
        "category": "accessoire",
        "sub_category": "bâtonnets",
        "target_species": ["orignal"],
        "format": "Bâtonnets",
        "product_url": "https://zone-ecotone.com/products/batonnets-odeur-durine-concentres-male-mature-de-buck-expert",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "olfactif"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Bâtonnets d'odeur d'urine concentrés jeune mâle orignal",
        "brand": "Buck Expert",
        "price": 14.99,
        "category": "accessoire",
        "sub_category": "bâtonnets",
        "target_species": ["orignal"],
        "format": "Bâtonnets",
        "product_url": "https://zone-ecotone.com/products/batonnets-dodeur-durine-concentres-jeune-male-de-buck-expert",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "olfactif"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine de jument en chaleur",
        "brand": "Buck Expert",
        "price": 34.99,
        "category": "urine",
        "sub_category": "leurre_sexuel",
        "target_species": ["orignal"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-de-jument-en-chaleur-de-buck-expert",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "sexuel"],
        "application_mode": "sol",
        "season": ["rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Bâtonnets d'odeur d'urine concentrés femelle orignal en chaleur",
        "brand": "Buck Expert",
        "price": 14.99,
        "category": "accessoire",
        "sub_category": "bâtonnets",
        "target_species": ["orignal"],
        "format": "Bâtonnets",
        "product_url": "https://zone-ecotone.com/products/batonnets-dodeur-durine-concentres-femelle-en-chaleur-de-buck-expert",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "sexuel"],
        "application_mode": "sol",
        "season": ["rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Leurre olfactif Smog Chevreuil ou Orignal",
        "brand": "Meunerie Soucy",
        "price": 19.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal", "chevreuil"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/leurre-olfactif-smog-chevreuil-ou-orignal-de-meunerie-soucy",
        "availability": "en_stock",
        "attraction_type": ["odeur", "olfactif"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Sac de sel naturel",
        "brand": "Sel Drummond",
        "price": 6.99,
        "category": "mineral",
        "sub_category": "sel",
        "target_species": ["orignal", "chevreuil"],
        "format": "Sac 13.6kg",
        "weight": 13600,
        "product_url": "https://zone-ecotone.com/products/sac-de-sel-blanc-naturel-13-6-kg-sel-drummond",
        "availability": "en_stock",
        "attraction_type": ["minéral", "sel"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Perles d'odeur",
        "brand": "Traktiq",
        "price": 7.99,
        "category": "accessoire",
        "sub_category": "perles",
        "target_species": ["orignal", "chevreuil"],
        "format": "Perles",
        "product_url": "https://zone-ecotone.com/products/perles-dodeur-de-traktiq",
        "availability": "en_stock",
        "attraction_type": ["odeur", "diffuseur"],
        "application_mode": "suspension",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Top saline",
        "brand": "Meunerie Soucy",
        "price": 12.99,
        "category": "mineral",
        "sub_category": "saline",
        "target_species": ["orignal", "chevreuil"],
        "format": "Poudre",
        "product_url": "https://zone-ecotone.com/products/top-saline-de-meunerie-soucy",
        "availability": "en_magasin",
        "attraction_type": ["minéral", "sel"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Vasière extrême 7kg Chevreuil",
        "brand": "Produits Extrêmes C.G.",
        "price": 37.99,
        "category": "mineral",
        "sub_category": "vasière",
        "target_species": ["chevreuil"],
        "format": "7kg",
        "weight": 7000,
        "product_url": "https://zone-ecotone.com/products/vasiere-extreme-7kg-8881-chevreuil-de-produits-extr-mes-c-g",
        "availability": "en_magasin",
        "attraction_type": ["minéral", "vasière"],
        "application_mode": "sol",
        "season": ["été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Chaudière minéraux 18kg Chevreuil",
        "brand": "Produits Extrêmes C.G.",
        "price": 59.99,
        "category": "mineral",
        "sub_category": "minéraux",
        "target_species": ["chevreuil"],
        "format": "18kg (Chaudière)",
        "weight": 18000,
        "product_url": "https://zone-ecotone.com/products/chaudiere-mineraux-18kg-chevreuil-de-produits-extremes-c-g",
        "availability": "en_magasin",
        "attraction_type": ["minéral", "nutritif"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Mélange Mud 7kg pour vasière Chevreuil",
        "brand": "Meunerie Soucy",
        "price": 29.99,
        "category": "mineral",
        "sub_category": "vasière",
        "target_species": ["chevreuil"],
        "format": "7kg",
        "weight": 7000,
        "product_url": "https://zone-ecotone.com/products/melange-mud-7kg-pour-vasiere-chevreuil-de-meunerie-soucy",
        "availability": "en_magasin",
        "attraction_type": ["minéral", "vasière"],
        "application_mode": "sol",
        "season": ["été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Liquide attractif noir intense chevreuil",
        "brand": "Maniaque de Prospection",
        "price": 24.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/liquide-attractif-noir-intense-chevreuil-par-maniaque-de-prospection",
        "availability": "en_magasin",
        "attraction_type": ["odeur", "intense"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Mixte attractif chevreuil, betteraves",
        "brand": "Maniaque de Prospection",
        "price": 24.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "Liquide/Mixte",
        "flavor": "Betteraves",
        "product_url": "https://zone-ecotone.com/products/mixte-attractif-chevreuil-betteraves-maniaque-de-prospection",
        "availability": "en_magasin",
        "attraction_type": ["odeur", "végétal"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Glande Tarsale en gel chasse au chevreuil",
        "brand": "Produits Extrêmes C.G.",
        "price": 14.99,
        "category": "gel",
        "sub_category": "leurre_sexuel",
        "target_species": ["chevreuil"],
        "format": "Gel",
        "product_url": "https://zone-ecotone.com/products/glande-tarsale-en-gel-chasse-au-chevreuil-extremes-cg",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "tronc",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Mixte attractif chevreuil, pommes",
        "brand": "Maniaque de Prospection",
        "price": 24.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "Liquide/Mixte",
        "flavor": "Pommes",
        "product_url": "https://zone-ecotone.com/products/mixte-attractif-chevreuil-pommes-maniaque-de-prospection",
        "availability": "en_stock",
        "attraction_type": ["odeur", "fruité"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Mixte attractif chevreuil, protéines",
        "brand": "Maniaque de Prospection",
        "price": 24.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "Liquide/Mixte",
        "flavor": "Protéines",
        "product_url": "https://zone-ecotone.com/products/mixte-attractif-chevreuil-proteines-par-maniaque-de-prospection",
        "availability": "en_stock",
        "attraction_type": ["nutritif", "protéines"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    
    # ========== PAGE 3 ==========
    {
        "id": generate_product_id(),
        "name": "Prospection chevreuil, minéraux 25kg",
        "brand": "Maniaque de Prospection",
        "price": 59.99,
        "category": "mineral",
        "sub_category": "minéraux",
        "target_species": ["chevreuil"],
        "format": "25kg",
        "weight": 25000,
        "product_url": "https://zone-ecotone.com/products/prospection-chevreuil-mineraux-25kg-par-maniaque-de-prospection",
        "availability": "en_magasin",
        "attraction_type": ["minéral", "nutritif"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Boîte minéraux pour chevreuil",
        "brand": "Produits Extrêmes C.G.",
        "price": 69.99,
        "category": "mineral",
        "sub_category": "minéraux",
        "target_species": ["chevreuil"],
        "format": "Boîte",
        "product_url": "https://zone-ecotone.com/products/boite-mineraux-pour-chevreuil-de-produits-extr-mes-c-g",
        "availability": "en_magasin",
        "attraction_type": ["minéral", "nutritif"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Bâtonnets d'encens Biche en chaleur",
        "brand": "Tink's",
        "price": 21.99,
        "category": "accessoire",
        "sub_category": "encens",
        "target_species": ["chevreuil"],
        "format": "Bâtonnets",
        "product_url": "https://zone-ecotone.com/products/batonnets-dencens-biche-en-chaleur-de-tinks",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "sexuel"],
        "application_mode": "brûlage",
        "season": ["rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine synthétique mixte",
        "brand": "Produits Extrêmes C.G.",
        "price": 20.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil", "orignal"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-synthetique-mixte-de-produits-extremes-c-g",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "olfactif"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine synthétique chevreuil",
        "brand": "Produits Extrêmes C.G.",
        "price": 20.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-synthetique-chevreuil-de-produits-extremes-c-g",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "olfactif"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine synthétique chevreuil mâle dominant",
        "brand": "Meunerie Soucy",
        "price": 19.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-synthetique-chevreuil-male-dominant-de-soucy",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine synthétique chevreuil jeune mâle",
        "brand": "Meunerie Soucy",
        "price": 19.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-synthetique-chevreuil-jeune-male-de-soucy",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine synthétique chevreuil femelle en chaleur",
        "brand": "Meunerie Soucy",
        "price": 19.99,
        "category": "urine",
        "sub_category": "leurre_sexuel",
        "target_species": ["chevreuil"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-synthetique-chevreuil-femelle-en-chaleur-de-soucy",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "sexuel"],
        "application_mode": "sol",
        "season": ["rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine synthétique chevreuil mâle dominant",
        "brand": "Buck Expert",
        "price": 14.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-synthetique-chevreuil-male-dominant-de-buck-expert",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine synthétique biche",
        "brand": "Buck Expert",
        "price": 14.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-synthetique-biche-de-buck-expert",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "olfactif"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine synthétique biche en chaleur",
        "brand": "Buck Expert",
        "price": 14.99,
        "category": "urine",
        "sub_category": "leurre_sexuel",
        "target_species": ["chevreuil"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-synthetique-biche-en-chaleur-de-buck-expert",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "sexuel"],
        "application_mode": "sol",
        "season": ["rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Bâtonnets d'odeur d'urine concentrés chevreuil mâle mature",
        "brand": "Buck Expert",
        "price": 14.99,
        "category": "accessoire",
        "sub_category": "bâtonnets",
        "target_species": ["chevreuil"],
        "format": "Bâtonnets",
        "product_url": "https://zone-ecotone.com/products/batonnets-dodeur-durine-concentres-chevreuil-male-mature-de-buck-expert",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Bâtonnets d'odeur d'urine concentrés chevreuil jeune mâle",
        "brand": "Buck Expert",
        "price": 14.99,
        "category": "accessoire",
        "sub_category": "bâtonnets",
        "target_species": ["chevreuil"],
        "format": "Bâtonnets",
        "product_url": "https://zone-ecotone.com/products/batonnets-dodeur-durine-concentres-chevreuil-jeune-male-de-buck-expert",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Bâtonnets d'odeur d'urine concentrés biche en chaleur",
        "brand": "Buck Expert",
        "price": 14.99,
        "category": "accessoire",
        "sub_category": "bâtonnets",
        "target_species": ["chevreuil"],
        "format": "Bâtonnets",
        "product_url": "https://zone-ecotone.com/products/batonnets-dodeur-durine-concentres-biche-en-chaleur-de-buck-expert",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "sexuel"],
        "application_mode": "sol",
        "season": ["rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Chaudière de minéraux pour chevreuil - 20 kg",
        "brand": "Meunerie Soucy",
        "price": 49.99,
        "category": "mineral",
        "sub_category": "minéraux",
        "target_species": ["chevreuil"],
        "format": "20kg (Chaudière)",
        "weight": 20000,
        "product_url": "https://zone-ecotone.com/products/chaudiere-de-mineraux-pour-chevreuil-20-kg-meunerie-soucy",
        "availability": "en_magasin",
        "attraction_type": ["minéral", "nutritif"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Minéraux Crack+ orignal ou chevreuil",
        "brand": "Buck Expert",
        "price": 19.99,
        "category": "mineral",
        "sub_category": "minéraux",
        "target_species": ["orignal", "chevreuil"],
        "format": "Poudre/Minéraux",
        "product_url": "https://zone-ecotone.com/products/mineraux-crack-de-buck-expert",
        "availability": "en_stock",
        "attraction_type": ["minéral", "nutritif"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Appâtage chevreuil Last meal 3KG",
        "brand": "Meunerie Soucy",
        "price": 19.99,
        "category": "granules",
        "sub_category": "appât",
        "target_species": ["chevreuil"],
        "format": "3kg",
        "weight": 3000,
        "product_url": "https://zone-ecotone.com/products/appatage-chevreuil-booster-last-meal-rehausseur-meunerie-soucy",
        "availability": "en_stock",
        "attraction_type": ["nutritif", "goût"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Leurre olfactif Buck addict 500ml",
        "brand": "Produits Extrêmes C.G.",
        "price": 31.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "500ml",
        "volume": 500,
        "product_url": "https://zone-ecotone.com/products/leurre-olfactif-buck-addict-500ml-de-produits-extremes-c-g",
        "availability": "en_stock",
        "attraction_type": ["odeur", "intense"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Leurre olfactif Bull addict 500ml",
        "brand": "Produits Extrêmes C.G.",
        "price": 31.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal"],
        "format": "500ml",
        "volume": 500,
        "product_url": "https://zone-ecotone.com/products/bull-addict-500ml-produits-extremes-c-g",
        "availability": "en_stock",
        "attraction_type": ["odeur", "intense"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Coulis à la menthe",
        "brand": "Meunerie Soucy",
        "price": 14.99,
        "category": "liquide",
        "sub_category": "coulis",
        "target_species": ["orignal", "chevreuil"],
        "format": "Liquide",
        "flavor": "Menthe",
        "product_url": "https://zone-ecotone.com/products/coulis-a-la-menthe-de-meunerie-soucy",
        "availability": "en_stock",
        "attraction_type": ["odeur", "végétal"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    
    # ========== PAGES 4-6 (Suite) ==========
    {
        "id": generate_product_id(),
        "name": "Top saline à la menthe",
        "brand": "Meunerie Soucy",
        "price": 12.99,
        "category": "mineral",
        "sub_category": "saline",
        "target_species": ["orignal", "chevreuil"],
        "format": "Poudre",
        "flavor": "Menthe",
        "product_url": "https://zone-ecotone.com/products/top-saline-de-meunerie-soucy-a-la-menthe",
        "availability": "en_magasin",
        "attraction_type": ["minéral", "sel"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine synthétique cervidés",
        "brand": "Tink's",
        "price": 17.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal", "chevreuil"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-synthetique-de-tinks",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "olfactif"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Bombe d'odeurs pour ours",
        "brand": "Meunerie Soucy",
        "price": 13.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["ours"],
        "format": "Aérosol",
        "product_url": "https://zone-ecotone.com/products/bombe-odeurs-pour-ours-meunerie-soucy",
        "availability": "en_stock",
        "attraction_type": ["odeur", "sucré"],
        "application_mode": "vaporisation",
        "season": ["printemps", "été"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Leurre olfactif à la menthe Aroma",
        "brand": "Meunerie Soucy",
        "price": 14.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal", "chevreuil"],
        "format": "Liquide",
        "flavor": "Menthe",
        "product_url": "https://zone-ecotone.com/products/leurre-olfactif-a-la-menthe-de-meunerie-soucy",
        "availability": "en_stock",
        "attraction_type": ["odeur", "végétal"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine synthétique jeune mâle",
        "brand": "Buck Expert",
        "price": 14.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-synthetique-jeune-male-de-buck-expert",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Prospection chevreuil, ensemble",
        "brand": "Maniaque de Prospection",
        "price": 44.99,
        "category": "kit",
        "sub_category": "ensemble",
        "target_species": ["chevreuil"],
        "format": "Kit complet",
        "product_url": "https://zone-ecotone.com/products/prospection-chevreuil-ensemble-par-maniaque-de-prospection",
        "availability": "en_magasin",
        "attraction_type": ["multiple"],
        "application_mode": "multiple",
        "season": ["été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Chaudière minéraux 18kg avec coulis Chevreuil ou Orignal",
        "brand": "Produits Extrêmes C.G.",
        "price": 69.99,
        "category": "mineral",
        "sub_category": "minéraux",
        "target_species": ["orignal", "chevreuil"],
        "format": "18kg + Coulis",
        "weight": 18000,
        "product_url": "https://zone-ecotone.com/products/chaudiere-mineraux-18kg-avec-coulis-chevreuil-ou-orignal-produits-extremes-c-g",
        "availability": "en_stock",
        "attraction_type": ["minéral", "nutritif"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Concentré d'odeur Bear Addiction pour ours",
        "brand": "Meunerie Soucy",
        "price": 18.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["ours"],
        "format": "Concentré",
        "variants": ["Castor", "Érable", "Anis"],
        "product_url": "https://zone-ecotone.com/products/concentre-dodeur-bear-addiction-pour-ours-meunerie-soucy",
        "availability": "en_stock",
        "attraction_type": ["odeur", "sucré"],
        "application_mode": "sol",
        "season": ["printemps", "été"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Coulis à la cerise noire Gravy",
        "brand": "Meunerie Soucy",
        "price": 14.99,
        "category": "liquide",
        "sub_category": "coulis",
        "target_species": ["orignal", "chevreuil", "ours"],
        "format": "Liquide",
        "flavor": "Cerise noire",
        "product_url": "https://zone-ecotone.com/products/coulis-a-la-cerise-noire-gravy-de-meunerie-soucy",
        "availability": "en_stock",
        "attraction_type": ["odeur", "fruité"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Leurre olfactif Open Bait",
        "brand": "Produits Extrêmes C.G.",
        "price": 24.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["ours"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/leurre-olfactif-open-bait-de-extremes-c-g",
        "availability": "en_stock",
        "attraction_type": ["odeur", "sucré"],
        "application_mode": "sol",
        "season": ["printemps", "été"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Coulis Fry Bear 20 litres 4 saveurs",
        "brand": "Meunerie Soucy",
        "price": 69.99,
        "category": "liquide",
        "sub_category": "coulis",
        "target_species": ["ours"],
        "format": "20 litres",
        "volume": 20000,
        "variants": ["Bacon", "Beigne sucré", "Érable", "Framboise"],
        "product_url": "https://zone-ecotone.com/products/coulis-fry-bear-de-meunerie-soucy-4-saveurs",
        "availability": "en_stock",
        "attraction_type": ["odeur", "sucré", "gras"],
        "application_mode": "sol",
        "season": ["printemps", "été"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Liquide attractif noir intense ours",
        "brand": "Maniaque de Prospection",
        "price": 20.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["ours"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/liquide-attractif-noir-intense-ours-par-maniaque-de-prospection",
        "availability": "en_magasin",
        "attraction_type": ["odeur", "intense"],
        "application_mode": "sol",
        "season": ["printemps", "été"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Kit ours",
        "brand": "Meunerie Soucy",
        "price": 58.99,
        "category": "kit",
        "sub_category": "ensemble",
        "target_species": ["ours"],
        "format": "Kit (Moulée 20kg + Mélasse 5kg + Attractant 750ml)",
        "product_url": "https://zone-ecotone.com/products/kit-ours-poche-moulee-20kg-melasse-5-kg-poudre-olfactive-attractant-ours-750-ml-meunerie-soucy",
        "availability": "en_stock",
        "attraction_type": ["multiple", "sucré"],
        "application_mode": "multiple",
        "season": ["printemps", "été"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine jeune mâle orignal Moose Master",
        "brand": "Produits Extrêmes C.G.",
        "price": 59.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal"],
        "format": "Liquide Premium",
        "product_url": "https://zone-ecotone.com/products/urine-dorignal-moose-master-produits-extremes-c-g",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine mâle orignal Moose Master",
        "brand": "Produits Extrêmes C.G.",
        "price": 59.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal"],
        "format": "Liquide Premium",
        "product_url": "https://zone-ecotone.com/products/urine-male-orignal-moose-master-produits-extremes-c-g",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Leurre olfactif brumisateur orignal dominant",
        "brand": "Tink's",
        "price": 21.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal"],
        "format": "Brumisateur",
        "product_url": "https://zone-ecotone.com/products/leurre-olfactif-brumisateur-orignal-dominant-tinks",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "vaporisation",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Bâtonnet odorant urine d'orignal mâle dominant Dominant Bull Moose",
        "brand": "Tink's",
        "price": 27.99,
        "category": "accessoire",
        "sub_category": "bâtonnets",
        "target_species": ["orignal"],
        "format": "Bâtonnets",
        "product_url": "https://zone-ecotone.com/products/batonnet-odorant-urine-dorignal-male-dominant-bull-moose-tinks",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine synthétique Mâle dominant chevreuil",
        "brand": "Produits Extrêmes C.G.",
        "price": 20.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-synthetique-male-dominant-chevreuil-produits-extremes-c-g",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine synthétique jeune mâle chevreuil",
        "brand": "Produits Extrêmes C.G.",
        "price": 20.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-synthetique-jeune-male-chevreuil-produits-extremes-c-g",
        "availability": "en_magasin",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Coulis carottes Gravy 4L chevreuil",
        "brand": "Meunerie Soucy",
        "price": 14.99,
        "category": "liquide",
        "sub_category": "coulis",
        "target_species": ["chevreuil"],
        "format": "4L",
        "volume": 4000,
        "flavor": "Carottes",
        "product_url": "https://zone-ecotone.com/products/coulis-carottes-gravy-4l-meunerie-soucy",
        "availability": "en_stock",
        "attraction_type": ["odeur", "végétal"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Appâtage chevreuil Last meal 12kg",
        "brand": "Meunerie Soucy",
        "price": 49.99,
        "category": "granules",
        "sub_category": "appât",
        "target_species": ["chevreuil"],
        "format": "12kg",
        "weight": 12000,
        "product_url": "https://zone-ecotone.com/products/appatage-chevreuil-last-meal-12kg-meunerie-soucy",
        "availability": "en_magasin",
        "attraction_type": ["nutritif", "goût"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Appâtage chevreuil Corde à buck",
        "brand": "Glands de Chêne",
        "price": 34.99,
        "category": "accessoire",
        "sub_category": "corde",
        "target_species": ["chevreuil"],
        "format": "Corde imprégnée",
        "product_url": "https://zone-ecotone.com/products/appatage-chevreuil-corde-a-buck-glands-de-chene",
        "availability": "en_magasin",
        "attraction_type": ["odeur", "diffuseur"],
        "application_mode": "suspension",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Appâtage Bloc pressé 11kg chevreuil ou orignal",
        "brand": "Glands de Chêne",
        "price": 34.99,
        "category": "bloc",
        "sub_category": "appât",
        "target_species": ["orignal", "chevreuil"],
        "format": "11kg (Bloc)",
        "weight": 11000,
        "product_url": "https://zone-ecotone.com/products/appatage-bloc-presse-11kg-chevreuil-ou-orignal-glands-de-chene",
        "availability": "en_magasin",
        "attraction_type": ["nutritif", "goût"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Appâtage liquide chevreuil saveur de soya",
        "brand": "Glands de Chêne",
        "price": 24.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "Liquide",
        "flavor": "Soya",
        "product_url": "https://zone-ecotone.com/products/appatage-liquide-chevreuil-saveur-de-soya-glands-de-chene",
        "availability": "en_magasin",
        "attraction_type": ["odeur", "végétal"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Gras végétal - Appâtage liquide chevreuil avec glands de chêne naturels",
        "brand": "Glands de Chêne",
        "price": 24.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "Liquide",
        "flavor": "Glands de chêne",
        "product_url": "https://zone-ecotone.com/products/appatage-liquide-chevreuil-avec-glands-de-chene-naturels-glands-de-chene",
        "availability": "en_magasin",
        "attraction_type": ["odeur", "végétal", "gras"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Minéraux soufre pur sac 2.5 kg",
        "brand": "Buck Expert",
        "price": 18.99,
        "category": "mineral",
        "sub_category": "soufre",
        "target_species": ["orignal", "chevreuil"],
        "format": "2.5kg",
        "weight": 2500,
        "product_url": "https://zone-ecotone.com/products/mineraux-soufre-pur-sac-2-5-kg-136shb-buck-expert",
        "availability": "en_magasin",
        "attraction_type": ["minéral"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Minéraux sel himalayen Nutri-Stone 2.5 kg",
        "brand": "Buck Expert",
        "price": 19.99,
        "category": "mineral",
        "sub_category": "sel",
        "target_species": ["orignal", "chevreuil"],
        "format": "2.5kg",
        "weight": 2500,
        "product_url": "https://zone-ecotone.com/products/mineraux-sel-himalayen-nutri-stone-2-5-kg-buck-expert",
        "availability": "en_stock",
        "attraction_type": ["minéral", "sel"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Minéraux à base d'urine d'orignal - Stimulateur",
        "brand": "Produits Extrêmes C.G.",
        "price": 24.99,
        "category": "mineral",
        "sub_category": "minéraux",
        "target_species": ["orignal"],
        "format": "Poudre/Minéraux",
        "product_url": "https://zone-ecotone.com/products/mineraux-a-base-durine-dorignal-stimulateur-produits-extremes-c-g",
        "availability": "en_stock",
        "attraction_type": ["minéral", "hormonal"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Minéraux concentrés attirer orignal ou chevreuil",
        "brand": "Meunerie Soucy",
        "price": 20.99,
        "category": "mineral",
        "sub_category": "minéraux",
        "target_species": ["orignal", "chevreuil"],
        "format": "Concentré",
        "product_url": "https://zone-ecotone.com/products/concentre-de-mineraux-attirer-orignal-ou-chevreuil-meunerie-soucy",
        "availability": "en_stock",
        "attraction_type": ["minéral", "nutritif"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Rock-Bloc mélange de minéraux durcissant",
        "brand": "Produits Extrêmes C.G.",
        "price": 34.99,
        "category": "bloc",
        "sub_category": "minéraux",
        "target_species": ["orignal", "chevreuil"],
        "format": "Bloc",
        "product_url": "https://zone-ecotone.com/products/rock-bloc-melange-de-mineraux-durcissant-produits-extremes-c-g",
        "availability": "en_stock",
        "attraction_type": ["minéral", "nutritif"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Acro-Kain pour saline poudre volatile de minéraux et sels",
        "brand": "Produits Extrêmes C.G.",
        "price": 10.99,
        "category": "mineral",
        "sub_category": "saline",
        "target_species": ["orignal", "chevreuil"],
        "format": "Poudre volatile",
        "product_url": "https://zone-ecotone.com/products/acro-kain-pour-saline-poudre-volatile-de-mineraux-et-sels-produits-extremes-c-g",
        "availability": "en_stock",
        "attraction_type": ["minéral", "sel"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Kit prospection pour saline orignal ou chevreuil exclusivité",
        "brand": "Produits Extrêmes C.G.",
        "price": 41.99,
        "category": "kit",
        "sub_category": "saline",
        "target_species": ["orignal", "chevreuil"],
        "format": "Kit complet",
        "product_url": "https://zone-ecotone.com/products/kit-prospection-pour-saline-orignal-ou-chevreuil-exclusivite-produits-extremes-c-g",
        "availability": "en_stock",
        "attraction_type": ["minéral", "multiple"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Complément de minéraux 100% naturel",
        "brand": "Maniaque de Prospection",
        "price": 18.99,
        "category": "mineral",
        "sub_category": "minéraux",
        "target_species": ["orignal", "chevreuil"],
        "format": "Poudre",
        "product_url": "https://zone-ecotone.com/products/complement-de-mineraux-100-naturel-maniaque-de-prospection",
        "availability": "en_stock",
        "attraction_type": ["minéral", "naturel"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Appât Leurre olfactif ours",
        "brand": "Maniaque de Prospection",
        "price": 25.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["ours"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/appat-leurre-olfactif-ours-maniaque-de-prospection",
        "availability": "en_magasin",
        "attraction_type": ["odeur", "sucré"],
        "application_mode": "sol",
        "season": ["printemps", "été"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Coulis Fry Bear attirer votre ours",
        "brand": "Produits Extrêmes C.G.",
        "price": 19.99,
        "category": "liquide",
        "sub_category": "coulis",
        "target_species": ["ours"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/coulis-fry-bear-attirer-votre-ours-extremes-cg",
        "availability": "en_magasin",
        "attraction_type": ["odeur", "sucré", "gras"],
        "application_mode": "sol",
        "season": ["printemps", "été"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Moulée appât pour ours 20 kg Econours",
        "brand": "Meunerie Soucy",
        "price": 21.99,
        "category": "granules",
        "sub_category": "moulée",
        "target_species": ["ours"],
        "format": "20kg",
        "weight": 20000,
        "product_url": "https://zone-ecotone.com/products/moulee-appat-pour-ours-20-kg-econours-meunerie-soucy",
        "availability": "en_magasin",
        "attraction_type": ["nutritif", "goût"],
        "application_mode": "sol",
        "season": ["printemps", "été"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Leurre Nutel'Ours appât ultra collant 3 kg attirer ours",
        "brand": "Meunerie Soucy",
        "price": 19.99,
        "category": "gel",
        "sub_category": "appât",
        "target_species": ["ours"],
        "format": "3kg",
        "weight": 3000,
        "product_url": "https://zone-ecotone.com/products/leurre-nutelours-appat-ultra-collant-3-kg-attirer-ours-meunerie-soucy",
        "availability": "en_magasin",
        "attraction_type": ["goût", "sucré"],
        "application_mode": "tronc",
        "season": ["printemps", "été"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Leurre glande pré orbitale chasse chevreuil",
        "brand": "Meunerie Soucy",
        "price": 19.99,
        "category": "liquide",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/leurre-glande-pre-orbitale-chasse-chevreuil-meunerie-soucy",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "tronc",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Granules urine synthétique Orignal Moose Scrape",
        "brand": "Produits Extrêmes C.G.",
        "price": 49.99,
        "category": "granules",
        "sub_category": "urine",
        "target_species": ["orignal"],
        "format": "Granules",
        "product_url": "https://zone-ecotone.com/products/granules-urine-synthetique-attirer-orignal-moose-scrap-extremescg",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Appâtage Corde à orignal",
        "brand": "Glands de Chêne",
        "price": 39.99,
        "category": "accessoire",
        "sub_category": "corde",
        "target_species": ["orignal"],
        "format": "Corde imprégnée",
        "product_url": "https://zone-ecotone.com/products/appatage-corde-a-orignal-glands-de-chene",
        "availability": "en_stock",
        "attraction_type": ["odeur", "diffuseur"],
        "application_mode": "suspension",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Souille liquide pour attirer orignal",
        "brand": "Buck Expert",
        "price": 29.99,
        "category": "liquide",
        "sub_category": "vasière",
        "target_species": ["orignal"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/souille-liquide-pour-attirer-orignal-buck-expert",
        "availability": "en_stock",
        "attraction_type": ["odeur", "vasière"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Leurre Top Souille attirer orignal",
        "brand": "Produits Extrêmes C.G.",
        "price": 36.99,
        "category": "liquide",
        "sub_category": "vasière",
        "target_species": ["orignal"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/leurre-top-souille-attirer-orignal-produits-extremes-c-g",
        "availability": "en_stock",
        "attraction_type": ["odeur", "vasière"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Phéromone synthétique Moose Spark 500 attirer orignal",
        "brand": "Glands de Chêne",
        "price": 34.99,
        "category": "urine",
        "sub_category": "leurre_sexuel",
        "target_species": ["orignal"],
        "format": "500ml",
        "volume": 500,
        "product_url": "https://zone-ecotone.com/products/pheromone-synthetique-moose-spark-500-attirer-orignal-glands-de-chene",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "phéromone"],
        "application_mode": "sol",
        "season": ["rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Phéromone synthétique Deer Spark 500 attirer CHEVREUIL",
        "brand": "Glands de Chêne",
        "price": 34.99,
        "category": "urine",
        "sub_category": "leurre_sexuel",
        "target_species": ["chevreuil"],
        "format": "500ml",
        "volume": 500,
        "product_url": "https://zone-ecotone.com/products/pheromone-synthetique-deer-spark-500-attirer-chevreuil-glands-de-chene",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "phéromone"],
        "application_mode": "sol",
        "season": ["rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Brume synthétique Hot Shot Power Moose",
        "brand": "Tink's",
        "price": 21.99,
        "category": "urine",
        "sub_category": "leurre_sexuel",
        "target_species": ["orignal"],
        "format": "Brumisateur",
        "product_url": "https://zone-ecotone.com/products/brume-synthetique-hot-shot-power-moose-tinks",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "sexuel"],
        "application_mode": "vaporisation",
        "season": ["rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Urine synthétique d'orignal mâle dominant Bull Moose",
        "brand": "Tink's",
        "price": 21.99,
        "category": "urine",
        "sub_category": "leurre_olfactif",
        "target_species": ["orignal"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/urine-synthetique-d-orignal-male-dominant-bull-moose-tinks",
        "availability": "en_stock",
        "attraction_type": ["hormonal", "territorial"],
        "application_mode": "sol",
        "season": ["pré-rut", "rut"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Farine de glands de chêne pour attirer Chevreuils",
        "brand": "Glands de Chêne",
        "price": 24.99,
        "category": "poudre",
        "sub_category": "appât",
        "target_species": ["chevreuil"],
        "format": "Farine",
        "product_url": "https://zone-ecotone.com/products/farine-de-glands-de-chene-pour-attirer-chevreuils-glands-de-chene",
        "availability": "en_stock",
        "attraction_type": ["nutritif", "goût"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Appâtage chevreuil Kit Automne pommes 40KG",
        "brand": "Meunerie Soucy",
        "price": 69.99,
        "category": "kit",
        "sub_category": "appât",
        "target_species": ["chevreuil"],
        "format": "40kg",
        "weight": 40000,
        "flavor": "Pommes",
        "product_url": "https://zone-ecotone.com/products/attirer-chevreuil-kit-automne-pommes-40kg-meunerie-soucy",
        "availability": "en_magasin",
        "attraction_type": ["nutritif", "fruité"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Appâtage chevreuil Kit Automne carottes 40KG",
        "brand": "Meunerie Soucy",
        "price": 69.99,
        "category": "kit",
        "sub_category": "appât",
        "target_species": ["chevreuil"],
        "format": "40kg",
        "weight": 40000,
        "flavor": "Carottes",
        "product_url": "https://zone-ecotone.com/products/attirer-chevreuil-kit-automne-carottes-40kg-meunerie-soucy",
        "availability": "en_magasin",
        "attraction_type": ["nutritif", "végétal"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Appâtage chevreuil Mangeoire suspendue tout-en-un 5 gallons",
        "brand": "Moultrie",
        "price": 99.99,
        "category": "accessoire",
        "sub_category": "mangeoire",
        "target_species": ["chevreuil"],
        "format": "5 gallons",
        "volume": 18900,
        "product_url": "https://zone-ecotone.com/products/appatage-chevreuil-mangeoire-suspendue-tout-en-un-5-gallons-moultrie",
        "availability": "en_magasin",
        "attraction_type": ["distributeur"],
        "application_mode": "suspension",
        "season": ["toute l'année"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Moulée pour chevreuil 25 kg saveur pommes",
        "brand": "Glands de Chêne",
        "price": 39.99,
        "category": "granules",
        "sub_category": "moulée",
        "target_species": ["chevreuil"],
        "format": "25kg",
        "weight": 25000,
        "flavor": "Pommes",
        "product_url": "https://zone-ecotone.com/products/moulee-pour-chevreuil-25-kg-glands-de-chene",
        "availability": "en_magasin",
        "attraction_type": ["nutritif", "fruité"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Poudre intense chevreuil saveurs variées 2 kg",
        "brand": "Maniaque de Prospection",
        "price": 19.99,
        "category": "poudre",
        "sub_category": "leurre_olfactif",
        "target_species": ["chevreuil"],
        "format": "2kg",
        "weight": 2000,
        "variants": ["Carotte", "Pomme"],
        "product_url": "https://zone-ecotone.com/products/poudre-intense-chevreuil-saveur-carotte-2kg-maniaque-de-prospection",
        "availability": "en_magasin",
        "attraction_type": ["odeur", "olfactif"],
        "application_mode": "sol",
        "season": ["automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Uri-booster attractant minéral liquide pour saline",
        "brand": "Produits Extrêmes C.G.",
        "price": 23.99,
        "category": "liquide",
        "sub_category": "saline",
        "target_species": ["orignal", "chevreuil"],
        "format": "Liquide",
        "product_url": "https://zone-ecotone.com/products/uri-booster-attractant-mineral-liquide-pour-saline-produits-extremes-c-g",
        "availability": "en_stock",
        "attraction_type": ["minéral", "hormonal"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Poudreuse pour salines attractant volatil pour chevreuil et orignal",
        "brand": "Glands de Chêne",
        "price": 19.99,
        "category": "poudre",
        "sub_category": "saline",
        "target_species": ["orignal", "chevreuil"],
        "format": "Poudre volatile",
        "product_url": "https://zone-ecotone.com/products/poudreuse-salines-attractant-volatil-pour-chevreuil-et-orignal-glands-de-chene",
        "availability": "en_stock",
        "attraction_type": ["minéral", "olfactif"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    },
    {
        "id": generate_product_id(),
        "name": "Wild stone minéraux durcissants attractant salines de chevreuil et d'orignal",
        "brand": "Glands de Chêne",
        "price": 24.99,
        "category": "bloc",
        "sub_category": "minéraux",
        "target_species": ["orignal", "chevreuil"],
        "format": "Bloc durcissant",
        "product_url": "https://zone-ecotone.com/products/wild-stone-mineraux-durcissants-attractant-salines-de-chevreuil-orignal-glands-de-chene",
        "availability": "en_stock",
        "attraction_type": ["minéral", "nutritif"],
        "application_mode": "sol",
        "season": ["printemps", "été", "automne"],
        "source": "Zone Ecotone"
    }
]

# Statistiques de la base de données
def get_ecotone_stats():
    total_products = len(ECOTONE_PRODUCTS)
    
    brands_count = {}
    categories_count = {}
    species_count = {}
    
    for product in ECOTONE_PRODUCTS:
        # Compter par marque
        brand = product.get("brand", "Unknown")
        brands_count[brand] = brands_count.get(brand, 0) + 1
        
        # Compter par catégorie
        category = product.get("category", "Unknown")
        categories_count[category] = categories_count.get(category, 0) + 1
        
        # Compter par espèce
        for species in product.get("target_species", []):
            species_count[species] = species_count.get(species, 0) + 1
    
    return {
        "total_products": total_products,
        "brands": brands_count,
        "categories": categories_count,
        "target_species": species_count,
        "price_range": {
            "min": min(p["price"] for p in ECOTONE_PRODUCTS),
            "max": max(p["price"] for p in ECOTONE_PRODUCTS),
            "avg": sum(p["price"] for p in ECOTONE_PRODUCTS) / total_products
        }
    }

if __name__ == "__main__":
    stats = get_ecotone_stats()
    print(f"\n=== STATISTIQUES ECOTONE ===")
    print(f"Total produits: {stats['total_products']}")
    print(f"\nPar marque:")
    for brand, count in sorted(stats['brands'].items(), key=lambda x: x[1], reverse=True):
        print(f"  - {brand}: {count}")
    print(f"\nPar catégorie:")
    for cat, count in sorted(stats['categories'].items(), key=lambda x: x[1], reverse=True):
        print(f"  - {cat}: {count}")
    print(f"\nPar espèce ciblée:")
    for species, count in sorted(stats['target_species'].items(), key=lambda x: x[1], reverse=True):
        print(f"  - {species}: {count}")
    print(f"\nGamme de prix: {stats['price_range']['min']}$ - {stats['price_range']['max']}$ (moyenne: {stats['price_range']['avg']:.2f}$)")
